#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
IGLOO_SHARED_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
DEFAULT_BIFROST_RS_DIR="${IGLOO_SHARED_ROOT}/../bifrost-rs"
if [[ -n "${BIFROST_RS_DIR:-}" ]]; then
  RESOLVED_BIFROST_RS_DIR="${BIFROST_RS_DIR}"
else
  RESOLVED_BIFROST_RS_DIR="${DEFAULT_BIFROST_RS_DIR}"
fi
BIFROST_RS_DIR="${RESOLVED_BIFROST_RS_DIR}"
WASM_PKG_DIR="${IGLOO_SHARED_BROWSER_WASM_OUT_DIR:-${IGLOO_SHARED_ROOT}/public/wasm}"
WASM_MODULES=(
  "crates/bifrost-bridge-wasm:bifrost_bridge_wasm"
  "crates/bifrost-profile-wasm:bifrost_profile_wasm"
)

if ! command -v wasm-pack >/dev/null 2>&1; then
  echo "error: wasm-pack is required (https://rustwasm.github.io/wasm-pack/installer/)" >&2
  exit 1
fi

if ! command -v clang >/dev/null 2>&1; then
  echo "error: clang is required to compile secp256k1 for wasm32-unknown-unknown" >&2
  exit 1
fi

if [[ ! -f "${BIFROST_RS_DIR}/Cargo.toml" ]]; then
  echo "error: bifrost-rs workspace not found at ${BIFROST_RS_DIR}" >&2
  echo "default workspace path: ${DEFAULT_BIFROST_RS_DIR}" >&2
  echo "override with: BIFROST_RS_DIR=/absolute/path/to/bifrost-rs npm run build:browser-wasm" >&2
  exit 1
fi

mkdir -p "${WASM_PKG_DIR}"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

for module_spec in "${WASM_MODULES[@]}"; do
  crate_path="${module_spec%%:*}"
  out_name="${module_spec##*:}"
  out_dir="${TMP_DIR}/${out_name}"

  (
    cd "${BIFROST_RS_DIR}"
    wasm-pack build "${crate_path}" \
      --target web \
      --out-dir "${out_dir}" \
      --out-name "${out_name}"
  )

  cp "${out_dir}/${out_name}.js" "${WASM_PKG_DIR}/${out_name}.js"
  cp "${out_dir}/${out_name}.d.ts" "${WASM_PKG_DIR}/${out_name}.d.ts"
  cp "${out_dir}/${out_name}_bg.wasm" "${WASM_PKG_DIR}/${out_name}_bg.wasm"
  # Content integrity (remediation PR20): embed the SHA-384 of the wasm
  # binary (and the glue JS) directly in the generated loader. The loader
  # fetches the wasm, recomputes SHA-384, and refuses to instantiate on a
  # mismatch — so a swapped _bg.wasm is rejected before it ever reaches
  # WebAssembly.instantiate. To bypass the check an attacker must also swap
  # this .mjs, which is same-origin and trusted at the origin/HTML level.
  wasm_sha384="$(openssl dgst -sha384 -binary "${WASM_PKG_DIR}/${out_name}_bg.wasm" | openssl base64 -A)"
  js_sha384="$(openssl dgst -sha384 -binary "${WASM_PKG_DIR}/${out_name}.js" | openssl base64 -A)"

  cat > "${WASM_PKG_DIR}/${out_name}_loader.mjs" <<EOF
// Auto-generated by build-bridge-wasm.sh. Do not edit.
// Embedded SHA-384 of ${out_name}_bg.wasm + ${out_name}.js captured at build time.
import init, * as wasm from './${out_name}.js';

const EXPECTED_WASM_SHA384 = 'sha384-${wasm_sha384}';
const EXPECTED_JS_SHA384 = 'sha384-${js_sha384}';

async function sha384Base64(buf) {
  const digest = await crypto.subtle.digest('SHA-384', buf);
  return 'sha384-' + btoa(String.fromCharCode(...new Uint8Array(digest)));
}

export default async function loadWasm(options = {}) {
  const wasmUrl = options.module_or_path ?? new URL('./${out_name}_bg.wasm', import.meta.url);
  const response = await fetch(wasmUrl);
  if (!response.ok) {
    throw new Error('wasm_fetch_failed: status ' + response.status);
  }
  const binary = await response.arrayBuffer();
  const actual = await sha384Base64(binary);
  if (actual !== EXPECTED_WASM_SHA384) {
    throw new Error(
      'wasm_integrity_check_failed: expected=' + EXPECTED_WASM_SHA384 + ' actual=' + actual,
    );
  }
  await init({ module_or_path: binary });
  return wasm;
}

// Re-export the wasm-bindgen named bindings so consumers that read this
// module's namespace (loader-core's assertModule, igloo-chrome's
// preloadedModule spread) still see the runtime/profile exports.
export * from './${out_name}.js';

export const __integrity = Object.freeze({
  wasmSha384: EXPECTED_WASM_SHA384,
  jsSha384: EXPECTED_JS_SHA384,
});
EOF
done

echo "ok: copied wasm artifacts to ${WASM_PKG_DIR}"
